name: Run Customer Service App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Initialize database
      run: |
        source venv/bin/activate
        python -c "from database import init_db; init_db()"

    - name: Run FastAPI (API test)
      run: |
        source venv/bin/activate
        nohup uvicorn api:app --host 0.0.0.0 --port 8000 &
        sleep 5
        curl http://localhost:8000/order/123456

    - name: Run Streamlit App (headless)
      run: |
        source venv/bin/activate
        streamlit run main.py &
        sleep 10
